GET  http://localhost:3000 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "nama": "Budi sudarsono",
    "email": "setyabudi@gmail.com",
    "Role": "Backend Eng"
}

###
PUT http://localhost:3000/api/users/01a0285a-9701-7d9c-9c17-d367b83cdf45 HTTP/1.1
Content-Type: application/json

{
    "nama": "andi sudarsonos",
    "email": "andi@gmail.com",
    "Role": "Manager"
}

###
GET http://localhost:3000/api/users/01a01011-9c01-76bc-92ce-86ce5cba4942 HTTP/1.1
Content-Type: application/json

###
DELETE  http://localhost:3000/api/users/01a01011-9c01-76bc-92ce-86ce5cba4942 HTTP/1.1
Content-Type: application/json



### Addres
GET http://localhost:3000/api/users/01a029c1-a754-7855-95e0-486890d707xe1/addresses HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/users/01a029c1-a754-7855-95e0-486890d707e1/addresses HTTP/1.1
Content-Type: application/json

{
    "label": "Rumah",
    "street": "Jl. Boscha Asrama Denma",
    "city": "Bandung"
}

###
PUT http://localhost:3000/api/users/01a029c1-a754-7855-95e0-486890d707e1/addresses/01a02a5e-4f50-7986-8bac-ca0fb2050b8e HTTP/1.1
Content-Type: application/json

{
    "label": "Rumah",
    "street": "Jl. Kumala gardern 1231",
    "city": "Bandung"
}

###
PATCH http://localhost:3000/api/users/01a029c1-a754-7855-95e0-486890d707e1/addresses/01a02a5e-4f50-7986-8bac-ca0fb2050b8e/default HTTP/1.1
Content-Type: application/json


###
DELETE  http://localhost:3000/api/users/01a029c1-a754-7855-95e0-486890d707e1/addresses/01a02a5e-4ea7-7213-8f60-8289fab55737 HTTP/1.1
Content-Type: application/json


### Product
GET http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/products/01a01012-1b99-7b61-8dbe-f7849a1b2517 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

{
    "nama": "Sembako",
    "harga" : 100000
}

###
PUT http://localhost:3000/api/products/01a01012-1b99-7b61-8dbe-f7849a1b2517 HTTP/1.1
Content-Type: application/json

{
    "nama": "Rookok",
    "harga" : 100000
}

###
DELETE http://localhost:3000/api/products/01a01012-1b99-7b61-8dbe-f7849a1b2517 HTTP/1.1
Content-Type: application/json
